version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: composer install -n --prefer-dist
      - run:
          name: "Reduce OpenSSL security level because RuneScape uses ancient encryption"
          command: sudo sed -i 's/SECLEVEL=2/SECLEVEL=1/g' /etc/ssl/openssl.cnf
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run:
          name: "Run tests"
          command: vendor/bin/phpunit test/
